import React, { useEffect, useState } from 'react'
import { Edit3, Plus, Save, Trash2, X } from 'lucide-react'
import { apiRequest } from '../lib/api.js'

const empty = { slug: '', nome: '', descricao: '', icone: 'shirt', preco: '', publicado: true, ordem: 0, variantesTexto: '' }
const parseVariants = text => text.split('\n').map(line => line.trim()).filter(Boolean).map((line, ordem) => { const [corNome, corHex, tamanho, imagemUrl, preco] = line.split('|').map(value => value.trim()); return { corNome, corHex, tamanho: tamanho || null, imagemUrl, preco: preco || null, ativo: true, ordem } })
const formatVariants = variants => variants.map(item => [item.corNome, item.corHex, item.tamanho || '', item.imagemUrl, item.preco ?? ''].join(' | ')).join('\n')

export default function AdminCafeProducts({ onStatus }) {
  const [items, setItems] = useState([]); const [form, setForm] = useState(empty)
  const load = () => apiRequest('/api/admin/produtos-cafe').then(setItems).catch(error => onStatus(error.message))
  useEffect(() => { load() }, [])
  const save = async event => { event.preventDefault(); try { const body = { ...form, preco: form.preco || null, variantes: parseVariants(form.variantesTexto) }; await apiRequest(form.id ? `/api/admin/produtos-cafe/${form.id}` : '/api/admin/produtos-cafe', { method: form.id ? 'PUT' : 'POST', body: JSON.stringify(body) }); setForm(empty); await load(); onStatus('Produto da loja salvo.') } catch (error) { onStatus(error.message) } }
  const remove = async item => { if (!confirm(`Excluir “${item.nome}” e todas as variantes?`)) return; try { await apiRequest(`/api/admin/produtos-cafe/${item.id}`, { method: 'DELETE' }); await load(); onStatus('Produto excluído.') } catch (error) { onStatus(error.message) } }
  return <div><div className="admin-heading"><div><span className="eyebrow">Loja virtual</span><h1>Produtos do Café</h1><p>Canecas e bonés usam cor; camisetas e moletons usam cor e tamanho.</p></div><button onClick={() => setForm(empty)}><Plus/> Novo produto</button></div>
    <form className="admin-form" onSubmit={save}><div className="admin-form-heading"><h2>{form.id ? 'Editar produto' : 'Cadastrar produto'}</h2>{form.id && <button type="button" onClick={() => setForm(empty)}><X/> Cancelar</button>}</div><div className="admin-form-grid"><label>Nome<input required value={form.nome} onChange={event => setForm({ ...form, nome: event.target.value })}/></label><label>Slug<input required pattern="[a-z0-9-]+" value={form.slug} onChange={event => setForm({ ...form, slug: event.target.value })}/></label><label>Preço padrão<input type="number" min="0" step="0.01" value={form.preco ?? ''} onChange={event => setForm({ ...form, preco: event.target.value })}/></label><label>Ordem<input type="number" value={form.ordem} onChange={event => setForm({ ...form, ordem: Number(event.target.value) })}/></label></div><label>Descrição<textarea rows="3" value={form.descricao} onChange={event => setForm({ ...form, descricao: event.target.value })}/></label><label>Variantes — uma por linha: Cor | #hex | Tamanho opcional | URL da imagem | Preço opcional<textarea required rows="8" placeholder="Marrom | #493326 | | /src/assets/images/products/caneca-marrom.png | 49.90" value={form.variantesTexto} onChange={event => setForm({ ...form, variantesTexto: event.target.value })}/></label><label className="admin-check"><input type="checkbox" checked={form.publicado} onChange={event => setForm({ ...form, publicado: event.target.checked })}/>Publicado</label><button className="admin-save"><Save/> Salvar</button></form>
    <div className="admin-table-wrap"><table><thead><tr><th>Ordem</th><th>Produto</th><th>Preço</th><th>Variantes</th><th>Status</th><th>Ações</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.ordem}</td><td><strong>{item.nome}</strong><small>{item.slug}</small></td><td>{item.preco == null ? 'Por variante' : Number(item.preco).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</td><td>{item.variantes.length}</td><td>{item.publicado ? 'Publicado' : 'Oculto'}</td><td><div className="admin-row-actions"><button aria-label="Editar" onClick={() => setForm({ ...item, variantesTexto: formatVariants(item.variantes) })}><Edit3/></button><button aria-label="Excluir" className="danger" onClick={() => remove(item)}><Trash2/></button></div></td></tr>)}</tbody></table></div>
  </div>
}
