import React,{useMemo,useState} from 'react'
import {ArrowLeft,BarChart3,Calculator,Download,Info,RotateCcw,Scale,ShieldCheck,Trophy} from 'lucide-react'
import {simulateCashVsInstallment} from '../lib/cashInstallmentSimulation.js'
import WinnerConfetti from './WinnerConfetti.jsx'
import FieldHelp from './FieldHelp.jsx'
import {cashHelp} from '../lib/simulatorFieldHelp.js'

const initial={productPrice:5121.11,cashDiscount:10,installments:12,downPayment:0,installmentTotal:5121.11,extraMonths:0,annualCdi:14.9,cashCdiPercent:110,installmentCdiPercent:110,cashAdminFee:0,installmentAdminFee:0,cashIncomeTax:20,installmentIncomeTax:20,cashLoading:0,installmentLoading:0,installmentPaymentSource:'income',cashFlowTiming:'beginning'}
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
function Field({label,name,values,errors,onChange,min,max,step='0.01',hint,children}){return <label className={`sim-field ${errors[name]?'invalid':''}`}><span>{label}</span><FieldHelp text={cashHelp[name]}/>{children||<input type="number" name={name} value={values[name]} min={min} max={max} step={step} onChange={onChange}/>} {errors[name]?<small className="field-error">{errors[name]}</small>:hint&&<small>{hint}</small>}</label>}
function Chart({timeline}){const w=900,h=320,p=48,max=Math.max(...timeline.flatMap(x=>[x.cashNet,x.installmentNet]),1),points=k=>timeline.map((r,i)=>`${p+i/Math.max(1,timeline.length-1)*(w-p*2)},${h-p-r[k]/max*(h-p*2)}`).join(' '),final=timeline.at(-1),x=w-p,cashY=h-p-final.cashNet/max*(h-p*2),installmentY=h-p-final.installmentNet/max*(h-p*2),close=Math.abs(cashY-installmentY)<30;return <div className="result-chart"><div className="chart-legend"><span className="legend-cash">À vista</span><span className="legend-installment">Parcelado</span></div><svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none">{[0,.25,.5,.75,1].map(l=><g key={l}><line x1={p} x2={w-p} y1={h-p-l*(h-p*2)} y2={h-p-l*(h-p*2)}/><text x="4" y={h-p-l*(h-p*2)+4}>{money.format(max*l).replace(',00','')}</text></g>)}<polyline className="chart-cash" points={points('cashNet')}/><polyline className="chart-installment" points={points('installmentNet')}/><circle className="chart-point-cash" cx={x} cy={cashY} r="6"/><circle className="chart-point-installment" cx={x} cy={installmentY} r="6"/><text className="chart-value chart-value-cash" x={x-12} y={cashY+(close&&cashY<installmentY?-10:15)} textAnchor="end">{money.format(final.cashNet)}</text><text className="chart-value chart-value-installment" x={x-12} y={installmentY+(close&&installmentY<cashY?-10:-10)} textAnchor="end">{money.format(final.installmentNet)}</text></svg><div className="chart-axis"><span>Mês 1</span><span>Mês {timeline.length}</span></div></div>}

export default function CashInstallmentSimulator(){const[values,setValues]=useState(initial),[submitted,setSubmitted]=useState(initial),[errors,setErrors]=useState({});const result=useMemo(()=>simulateCashVsInstallment(submitted),[submitted]);const change=e=>setValues(v=>({...v,[e.target.name]:e.target.value}));const submit=e=>{e.preventDefault();const next=simulateCashVsInstallment(values);setErrors(next.errors);if(!Object.keys(next.errors).length)setSubmitted({...values})};const reset=()=>{setValues(initial);setSubmitted(initial);setErrors({})};const download=async()=>{const{generateCashInstallmentPdf}=await import('../lib/cashInstallmentReport.js');await generateCashInstallmentPdf(result,submitted)}
return <div className="simulator-page cash-installment-page"><header className="simulator-topbar"><a href="/"><ArrowLeft size={18}/> Voltar ao site</a><strong><span>CS</span>Café com Sardinha</strong></header><section className="simulator-hero cash-hero"><div><span className="eyebrow">Simulador financeiro</span><h1>À vista ou a prazo?</h1><p>Descubra se o desconto compensa mais do que manter o dinheiro investido, com fluxos de caixa comparáveis e premissas transparentes.</p></div><Scale size={76}/></section>
<main className="simulator-main"><form className="simulator-form" onSubmit={submit}><div className="form-intro"><div><span className="eyebrow">Suas premissas</span><h2>Configure a compra</h2></div><button type="button" onClick={reset}><RotateCcw size={16}/> Restaurar padrões</button></div>
<fieldset><legend>Compra e parcelamento</legend><div className="field-grid"><Field label="Valor do produto (R$)" name="productPrice" min="1" max="100000000" values={values} errors={errors} onChange={change}/><Field label="Desconto à vista (%)" name="cashDiscount" min="0" max="90" values={values} errors={errors} onChange={change}/><Field label="Número de parcelas" name="installments" min="1" max="120" step="1" values={values} errors={errors} onChange={change}/><Field label="Total da compra parcelada (R$)" name="installmentTotal" min="1" max="200000000" values={values} errors={errors} onChange={change} hint="Permite juros ou preço diferente no parcelamento."/><Field label="Entrada no parcelamento (R$)" name="downPayment" min="0" max="100000000" values={values} errors={errors} onChange={change}/><Field label="Meses adicionais após parcelas" name="extraMonths" min="0" max="600" step="1" values={values} errors={errors} onChange={change}/><Field label="Origem do pagto das parcelas" name="installmentPaymentSource" values={values} errors={errors} onChange={change}><select name="installmentPaymentSource" value={values.installmentPaymentSource} onChange={change}><option value="income">Renda mensal</option><option value="investment">Retirar do investimento</option></select></Field><Field label="Momento dos fluxos mensais" name="cashFlowTiming" values={values} errors={errors} onChange={change}><select name="cashFlowTiming" value={values.cashFlowTiming} onChange={change}><option value="beginning">Início do mês</option><option value="end">Fim do mês</option></select></Field></div></fieldset>
<fieldset><legend>Mercado</legend><div className="field-grid"><Field label="CDI anual estimado (%)" name="annualCdi" min="0" max="100" values={values} errors={errors} onChange={change}/></div></fieldset>
<fieldset className="scenario-cdb scenario-cash"><legend>Cenário 1 — Compra à vista</legend><div className="field-grid"><Field label="Rentabilidade (% do CDI)" name="cashCdiPercent" min="0" max="300" values={values} errors={errors} onChange={change}/><Field label="Taxa administrativa anual (%)" name="cashAdminFee" min="0" max="20" values={values} errors={errors} onChange={change}/><Field label="IR sobre rendimentos (%)" name="cashIncomeTax" min="0" max="100" values={values} errors={errors} onChange={change}/><Field label="Carregamento dos aportes (%)" name="cashLoading" min="0" max="50" values={values} errors={errors} onChange={change}/></div></fieldset>
<fieldset className="scenario-installment"><legend>Cenário 2 — Compra parcelada</legend><div className="field-grid"><Field label="Rentabilidade (% do CDI)" name="installmentCdiPercent" min="0" max="300" values={values} errors={errors} onChange={change}/><Field label="Taxa administrativa anual (%)" name="installmentAdminFee" min="0" max="20" values={values} errors={errors} onChange={change}/><Field label="IR sobre rendimentos (%)" name="installmentIncomeTax" min="0" max="100" values={values} errors={errors} onChange={change}/><Field label="Carregamento inicial (%)" name="installmentLoading" min="0" max="50" values={values} errors={errors} onChange={change}/></div></fieldset>
{errors.installmentPaymentSource&&<div className="form-validation"><Info size={18}/>{errors.installmentPaymentSource}</div>}<div className="form-notice"><Info size={18}/><p>Quando as parcelas saem da renda mensal, o cenário à vista investe mensalmente o mesmo valor, igualando o esforço de caixa. Quando saem do investimento, cada parcela reduz o saldo parcelado.</p></div><button className="simulate-button"><BarChart3 size={19}/> Calcular e atualizar gráfico</button></form>
{result.summary&&<section className="simulator-results"><div className="result-heading"><div><span className="eyebrow">Resultado líquido estimado</span><h2>Comparação ao fim de {result.timeline.length} meses</h2></div></div><div className="result-cards"><article className={result.summary.cashNet>result.summary.installmentNet?'winner-card':''}>{result.summary.cashNet>result.summary.installmentNet&&<><WinnerConfetti/><span className="trophy-badge" aria-label="Cenário vencedor"><Trophy/></span></>}<small>Comprar à vista</small><strong>{money.format(result.summary.cashNet)}</strong></article><article className={result.summary.installmentNet>result.summary.cashNet?'winner-card':''}>{result.summary.installmentNet>result.summary.cashNet&&<><WinnerConfetti/><span className="trophy-badge" aria-label="Cenário vencedor"><Trophy/></span></>}<small>Comprar parcelado</small><strong>{money.format(result.summary.installmentNet)}</strong></article><article className={result.summary.difference>=0?'positive':'negative'}><small>Diferença à vista − parcelado</small><strong>{money.format(result.summary.difference)}</strong></article></div><Chart timeline={result.timeline}/><div className="result-details"><div><span>Preço à vista</span><b>{money.format(result.summary.cashPrice)}</b></div><div><span>Desconto</span><b>{money.format(result.summary.discountValue)}</b></div><div><span>Valor da parcela</span><b>{money.format(result.summary.installment)}</b></div><div><span>Valor financiado</span><b>{money.format(result.summary.financedAmount)}</b></div></div><div className="method-note"><ShieldCheck size={22}/><p><strong>Comparação consistente:</strong> o cálculo corrige a omissão do script original e considera explicitamente de onde saem as parcelas.</p></div><button className="download-report" type="button" onClick={download}><Download size={18}/> Baixar memória de cálculo em PDF</button></section>}</main></div>}
