import React,{useEffect,useMemo,useRef,useState} from 'react'
import {ArrowLeft,ArrowRight,BarChart3,Calculator,Info,Pencil,Plus,Trash2,X} from 'lucide-react'
import {simulateFixedIncome} from './lib/fixedIncomeSimulation.js'
import {fixedHelp} from './lib/simulatorFieldHelp.js'

const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),pct=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:4})
const today=new Date().toISOString().slice(0,10),future=new Date(new Date().setFullYear(new Date().getFullYear()+2)).toISOString().slice(0,10)
const defaults={investment:10000,scenarios:{conservative:{ipca:4,selic:10,cdi:9.9},realistic:{ipca:5,selic:12,cdi:11.9},optimistic:{ipca:7,selic:15,cdi:14.9}}}
const fallback={titleTypes:[{id:6,nm_titulo_tipo:'CDB'},{id:2,nm_titulo_tipo:'LCI',fg_isento:true},{id:3,nm_titulo_tipo:'LCA',fg_isento:true},{id:1,nm_titulo_tipo:'LCD',fg_isento:true},{id:4,nm_titulo_tipo:'DEBÊNTURE INCENTIVADA',fg_isento:true},{id:5,nm_titulo_tipo:'DEBÊNTURE'},{id:7,nm_titulo_tipo:'CRI'},{id:8,nm_titulo_tipo:'CRA'},{id:9,nm_titulo_tipo:'FIDC'},{id:10,nm_titulo_tipo:'LF'},{id:11,nm_titulo_tipo:'LC'},{id:12,nm_titulo_tipo:'TESOURO DIRETO'}],formats:[{id:1,nm_indexador_formato:'IPCA+',id_indexador:1},{id:2,nm_indexador_formato:'SELIC+',id_indexador:2},{id:3,nm_indexador_formato:'% do CDI',id_indexador:3},{id:4,nm_indexador_formato:'CDI+',id_indexador:3},{id:5,nm_indexador_formato:'PRÉ',id_indexador:null}]}
const blank=()=>({titleTypeId:6,formatId:3,rate:110,applicationDate:today,maturityDate:future,issuer:'Banco emissor'}),labels={conservative:'Conservador',realistic:'Realista',optimistic:'Otimista'}
const productTone=id=>`rf-type-${Number(id)}`
const productHeadline=row=>{const rate=pct.format(+row.vr_taxa);if(+row.id_indexador_formato===3)return `${row.nm_titulo_tipo} ${rate}% CDI`;if(+row.id_indexador_formato===5)return `${row.nm_titulo_tipo} ${rate}% a.a.`;return `${row.nm_titulo_tipo} ${row.nm_indexador_formato} ${rate}%`}
const sameProduct=(a,b)=>Number(a.titleTypeId)===Number(b.titleTypeId)&&Number(a.formatId)===Number(b.formatId)&&Number(a.rate)===Number(b.rate)&&String(a.issuer).trim().toLocaleLowerCase('pt-BR')===String(b.issuer).trim().toLocaleLowerCase('pt-BR')&&a.applicationDate===b.applicationDate&&a.maturityDate===b.maturityDate
function Chart({rows}){if(!rows.length)return null;const max=Math.max(...rows.map(r=>+r.vr_liquido_acumulado),1);return <div className="result-chart rf-chart"><div className="chart-legend"><span className="legend-rf">Valor líquido no vencimento</span></div><div className="rf-bars">{rows.map((r,i)=><div className="rf-bar-row" key={r.id_titulo}><div className="rf-bar-label"><b>{r.nm_titulo_tipo}</b><small>{r.nm_emissor}</small></div><div className="rf-bar-track"><span style={{width:`${Math.max(8,+r.vr_liquido_acumulado/max*100)}%`,background:`hsl(${204-i*18} 78% ${38+i*4}%)`}}><em>{money.format(+r.vr_liquido_acumulado)}</em></span></div></div>)}</div></div>}
export default function FixedIncomeSimulator(){
 const[premises,setPremises]=useState(defaults),[step,setStep]=useState(1),[draft,setDraft]=useState(blank),[products,setProducts]=useState([]),[editingId,setEditingId]=useState(null),[scenario,setScenario]=useState('realistic'),[sort,setSort]=useState('net-desc'),[error,setError]=useState(''),formRef=useRef(null)
 const options=fallback
 useEffect(()=>{const helpByLabel={'Valor do investimento (R$)':fixedHelp.investment,IPCA:fixedHelp.scenario,SELIC:fixedHelp.scenario,CDI:fixedHelp.scenario,'Tipo de título':fixedHelp.titleType,Rentabilidade:fixedHelp.format,'Taxa oferecida (%)':fixedHelp.rate,Emissor:fixedHelp.issuer,'Data da aplicação':fixedHelp.applicationDate,'Data do vencimento':fixedHelp.maturityDate};document.querySelectorAll('.fixed-income-page .sim-field').forEach(field=>{const label=field.querySelector(':scope > span')?.textContent?.trim();if(helpByLabel[label])field.dataset.help=helpByLabel[label]})},[step,editingId])
 const results=useMemo(()=>simulateFixedIncome({...premises,products,options}),[premises,products])
 const selected=useMemo(()=>{const id={conservative:1,realistic:2,optimistic:3}[scenario];return results.filter(r=>+r.id_cenario===id).sort((a,b)=>sort==='net-desc'?+b.vr_liquido_acumulado- +a.vr_liquido_acumulado:sort==='rate-desc'?+b.pc_taxa_liquida_acumulada- +a.pc_taxa_liquida_acumulada:sort==='maturity'?String(a.dt_vencimento).localeCompare(String(b.dt_vencimento)):String(a.nm_emissor).localeCompare(String(b.nm_emissor),'pt-BR'))},[results,scenario,sort])
 const setIndex=(s,i,v)=>setPremises(p=>({...p,scenarios:{...p.scenarios,[s]:{...p.scenarios[s],[i]:v}}}))
 const add=e=>{e.preventDefault();setError('');if(+premises.investment<100)return setError('Informe um investimento de pelo menos R$ 100.');if(!draft.issuer.trim())return setError('Informe o emissor.');if(new Date(draft.maturityDate)<=new Date(draft.applicationDate))return setError('O vencimento precisa ser posterior à aplicação.');if(products.some(product=>+product.id!==+editingId&&sameProduct(product,draft)))return setError('Este título já foi adicionado com os mesmos dados. Altere algum campo para incluí-lo novamente.');const format=options.formats.find(f=>+f.id===+draft.formatId);setProducts(p=>editingId===null?[...p,{...draft,id:Math.max(0,...p.map(x=>+x.id))+1,indexerId:format?.id_indexador}]:p.map(x=>+x.id===+editingId?{...draft,id:x.id,indexerId:format?.id_indexador}:x));setDraft(blank());setEditingId(null)}
 const edit=product=>{if(!product)return;setDraft({...product});setEditingId(product.id);setError('');window.requestAnimationFrame(()=>formRef.current?.scrollIntoView({behavior:'smooth',block:'start'}))}
 const cancelEdit=()=>{setDraft(blank());setEditingId(null);setError('')}
 const remove=row=>{if(!window.confirm(`Tem certeza que deseja excluir o título ${row.nm_titulo_tipo} de ${row.nm_emissor}?`))return;setProducts(p=>p.filter(x=>+x.id!==+row.id_titulo));if(+editingId===+row.id_titulo)cancelEdit()}
 return <div className="simulator-page fixed-income-page"><header className="simulator-topbar"><a href="/"><ArrowLeft size={18}/> Voltar ao site</a><strong><span>CS</span>Café com Sardinha</strong></header><section className="simulator-hero rf-hero"><div><span className="eyebrow">Simulador financeiro</span><h1>Compare títulos de renda fixa</h1><p>Coloque CDB, LCI, LCA, Tesouro e outros produtos lado a lado, considerando prazo, imposto e cenário econômico.</p></div><BarChart3 size={76}/></section><main className="simulator-main"><div className="rf-stepper"><span className={step===1?'active':'done'}><b>1</b>Investimento e cenários</span><i/><span className={step===2?'active':''}><b>2</b>Títulos e comparação</span></div>
 {step===1?<form className="simulator-form" onSubmit={e=>{e.preventDefault();if(+premises.investment>=100){setError('');setStep(2)}else setError('Informe um investimento de pelo menos R$ 100.')}}><div className="form-intro"><div><span className="eyebrow">Etapa 1</span><h2>Defina as premissas</h2></div></div><fieldset><legend>Quanto será investido?</legend><div className="field-grid"><label className="sim-field"><span>Valor do investimento (R$)</span><input type="number" min="100" max="1000000000" step="0.01" value={premises.investment} onChange={e=>setPremises(p=>({...p,investment:e.target.value}))}/><small>O mesmo valor será aplicado em todos os títulos.</small></label></div></fieldset><fieldset className="rf-scenarios"><legend>Projeções anuais dos indexadores (%)</legend><p className="fieldset-help">Personalize as projeções. O cenário Realista será mostrado primeiro.</p><div className="rf-scenario-grid">{Object.entries(labels).map(([k,label])=><section className={k==='realistic'?'realistic':''} key={k}><h3>{label}</h3>{['ipca','selic','cdi'].map(i=><label className="sim-field" key={i}><span>{i.toUpperCase()}</span><input type="number" min="0" max="100" step="0.01" value={premises.scenarios[k][i]} onChange={e=>setIndex(k,i,e.target.value)}/></label>)}</section>)}</div></fieldset>{error&&<div className="form-validation"><Info size={18}/>{error}</div>}<button className="simulate-button">Continuar para os títulos <ArrowRight size={19}/></button></form>:
 <><form ref={formRef} className={`simulator-form ${editingId!==null?'rf-editing':''}`} onSubmit={add}><div className="form-intro"><div><span className="eyebrow">Etapa 2</span><h2>{editingId!==null?'Edite o título':'Adicione os títulos'}</h2></div><button type="button" onClick={()=>setStep(1)}>Editar premissas</button></div>{editingId!==null&&<div className="rf-edit-notice"><Pencil size={17}/><span>Você está alterando um produto já adicionado.</span><button type="button" onClick={cancelEdit}><X size={16}/> Cancelar edição</button></div>}<fieldset><legend>Dados do produto</legend><div className="field-grid"><label className="sim-field"><span>Tipo de título</span><select value={draft.titleTypeId} onChange={e=>setDraft(d=>({...d,titleTypeId:e.target.value}))}>{options.titleTypes.map(x=><option value={x.id} key={x.id}>{x.nm_titulo_tipo}{x.fg_isento?' — isento':''}</option>)}</select></label><label className="sim-field"><span>Rentabilidade</span><select value={draft.formatId} onChange={e=>setDraft(d=>({...d,formatId:e.target.value}))}>{options.formats.map(x=><option value={x.id} key={x.id}>{x.nm_indexador_formato}</option>)}</select></label><label className="sim-field"><span>Taxa oferecida (%)</span><input type="number" min="0" max="500" step="0.01" value={draft.rate} onChange={e=>setDraft(d=>({...d,rate:e.target.value}))}/><small>{+draft.formatId===3?'Ex.: 110 para 110% do CDI':'Ex.: 6,20 para indexador + 6,20%'}</small></label><label className="sim-field"><span>Emissor</span><input maxLength="80" value={draft.issuer} onChange={e=>setDraft(d=>({...d,issuer:e.target.value}))}/></label><label className="sim-field"><span>Data da aplicação</span><input type="date" value={draft.applicationDate} onChange={e=>setDraft(d=>({...d,applicationDate:e.target.value}))}/></label><label className="sim-field"><span>Data do vencimento</span><input type="date" min={draft.applicationDate} value={draft.maturityDate} onChange={e=>setDraft(d=>({...d,maturityDate:e.target.value}))}/></label></div></fieldset>{error&&<div className="form-validation"><Info size={18}/>{error}</div>}<button className="simulate-button">{editingId!==null?<Pencil size={19}/>:<Plus size={19}/>} {editingId!==null?'Salvar alterações e recalcular':'Adicionar e simular'}</button></form>
 {products.length>0&&<section className="simulator-results"><div className="result-heading"><div><span className="eyebrow">Comparação automática</span><h2>{products.length} {products.length===1?'título adicionado':'títulos adicionados'}</h2></div><div className="rf-controls"><label>Cenário<select value={scenario} onChange={e=>setScenario(e.target.value)}>{Object.entries(labels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>Ordenar por<select value={sort} onChange={e=>setSort(e.target.value)}><option value="net-desc">Maior valor líquido</option><option value="rate-desc">Maior rentabilidade</option><option value="maturity">Vencimento</option><option value="issuer">Emissor</option></select></label></div></div><div className="rf-product-list">{selected.map((r,i)=><article className={`${i===0?'rf-best ':''}${productTone(r.id_titulo_tipo)}`} key={r.id_titulo}><span className="rf-rank">{i+1}º</span><div className="rf-product-identity"><h3>{productHeadline(r)}</h3><div className="rf-title-info"><span><small>Emissor</small><b>{r.nm_emissor}</b></span><span><small>IR</small><b>{pct.format(+r.pc_aliquota_ir)}%</b></span></div></div><div className="rf-main-metric"><small>Rentabilidade líquida</small><strong>{pct.format(+r.pc_taxa_liquida_acumulada)}%</strong></div><div className="rf-main-metric"><small>Valor líquido</small><strong>{money.format(+r.vr_liquido_acumulado)}</strong></div><div className="rf-day-metrics"><span><small>Dias úteis</small><b>{Number(r.nr_dias_uteis).toLocaleString('pt-BR')}</b></span><span><small>Dias corridos</small><b>{Number(r.nr_dias_corridos).toLocaleString('pt-BR')}</b></span></div><div className="rf-card-actions"><button type="button" aria-label={`Editar ${r.nm_emissor}`} title="Editar título" onClick={()=>edit(products.find(x=>+x.id===+r.id_titulo))}><Pencil size={17}/></button><button type="button" aria-label={`Remover ${r.nm_emissor}`} title="Remover título" onClick={()=>remove(r)}><Trash2 size={18}/></button></div></article>)}</div><Chart rows={selected}/><div className="method-note"><Calculator size={22}/><p><strong>Metodologia do cálculo:</strong> considera prazo em dias úteis, tributação regressiva, isenção e capitalização de cada título.</p></div></section>}</>}</main></div>
}
